// DC.10 — Decision Brief Word template (server-side).
//
// Renders a clean, professional .docx from canonical Decision Case data.
// No Copilot raw output, no encrypted values, no secrets. The brief is a
// downstream snapshot — the source of truth remains the Decision Case in
// BTPM.

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Header,
  Footer,
  PageNumber,
  LevelFormat,
  ExternalHyperlink,
  PageBreak,
} from "https://esm.sh/docx@8.5.0";

import type { DecisionBriefData } from "./dataMapper.ts";

const FONT = "Calibri";

function fmtDate(s: string | null | undefined): string {
  if (!s) return "—";
  try {
    const d = new Date(s);
    if (Number.isNaN(d.getTime())) return s as string;
    return d.toISOString().slice(0, 10);
  } catch {
    return s as string;
  }
}

function p(text: string, opts: { bold?: boolean; size?: number; color?: string } = {}) {
  return new Paragraph({
    children: [
      new TextRun({
        text,
        font: FONT,
        bold: opts.bold,
        size: opts.size ?? 22,
        color: opts.color,
      }),
    ],
    spacing: { after: 80 },
  });
}

function heading(text: string, level: typeof HeadingLevel[keyof typeof HeadingLevel] = HeadingLevel.HEADING_2) {
  return new Paragraph({
    heading: level,
    children: [new TextRun({ text, font: FONT })],
  });
}

function bodyOrPlaceholder(text: string | null | undefined, placeholder = "Not specified."): Paragraph[] {
  const v = (text ?? "").trim();
  if (!v) return [p(placeholder, { color: "808080" })];
  // Split paragraphs on blank lines so multi-paragraph content reads well.
  return v
    .split(/\n{2,}/)
    .map((block) => block.replace(/\s+\n/g, "\n").trim())
    .filter(Boolean)
    .map((block) => p(block));
}

function bulletList(items: string[]): Paragraph[] {
  if (items.length === 0) return [p("None.", { color: "808080" })];
  return items.map(
    (t) =>
      new Paragraph({
        numbering: { reference: "bullets", level: 0 },
        children: [new TextRun({ text: t, font: FONT, size: 22 })],
      }),
  );
}

function linkParagraph(label: string, url: string | null | undefined): Paragraph {
  if (!url) {
    return new Paragraph({
      numbering: { reference: "bullets", level: 0 },
      children: [new TextRun({ text: label, font: FONT, size: 22 })],
    });
  }
  return new Paragraph({
    numbering: { reference: "bullets", level: 0 },
    children: [
      new TextRun({ text: `${label} — `, font: FONT, size: 22 }),
      new ExternalHyperlink({
        link: url,
        children: [
          new TextRun({
            text: url,
            font: FONT,
            size: 22,
            style: "Hyperlink",
            color: "1F4E79",
            underline: {},
          }),
        ],
      }),
    ],
  });
}

function statusLabel(v: string | null | undefined): string {
  if (!v) return "—";
  return v.replace(/_/g, " ");
}

export async function buildDecisionBriefDocxBuffer(d: DecisionBriefData): Promise<Uint8Array> {
  const titleLine = `Decision Brief — ${d.decisionCase.title}`;

  const children: Paragraph[] = [
    // Title / cover header block
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: d.organizationName || "BTPM",
          font: FONT,
          size: 20,
          color: "808080",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 120, after: 60 },
      children: [
        new TextRun({ text: "Decision Brief", font: FONT, bold: true, size: 40 }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: d.package.title || d.decisionCase.title,
          font: FONT,
          size: 28,
          color: "2E5984",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 80, after: 280 },
      children: [
        new TextRun({
          text: `${d.projectName} · Package v${d.package.versionNumber} · Generated ${fmtDate(d.generatedAt)}`,
          font: FONT,
          size: 20,
          color: "808080",
        }),
      ],
    }),

    // Summary table-like list (rendered as paragraphs for portability)
    heading("Decision Case Summary", HeadingLevel.HEADING_2),
    p(`Decision case: ${d.decisionCase.title}`),
    p(`Project: ${d.projectName}`),
    p(`Stage: ${statusLabel(d.decisionCase.stage)}`),
    p(`Target decision date: ${fmtDate(d.decisionCase.targetDecisionDate)}`),
    p(`Event type: ${d.decisionCase.eventType || "—"}`),
    p(`Package status: ${statusLabel(d.package.status)}`),
    p(`Audience: ${d.package.audience || "—"}`),
    p(`Generated by: ${d.generatedByLabel}`),

    // Executive Summary
    heading("Executive Summary"),
    ...bodyOrPlaceholder(d.package.executiveSummary),

    // Decision Question
    heading("Decision Question"),
    ...bodyOrPlaceholder(
      d.package.decisionQuestion || d.decisionCase.decisionQuestion,
    ),

    // Background and Context
    heading("Background and Context"),
    ...bodyOrPlaceholder(d.package.background || d.decisionCase.background),

    // Options Considered
    heading("Options Considered"),
    ...bodyOrPlaceholder(d.package.options),

    // Recommendation
    heading("Recommendation"),
    ...bodyOrPlaceholder(d.package.recommendation),

    // Decision Ask
    heading("Decision Ask"),
    ...bodyOrPlaceholder(d.package.decisionAsk),

    // Evidence and Context Summary
    heading("Evidence and Context Summary"),
    ...bodyOrPlaceholder(d.package.evidenceSummary, "No evidence summary provided."),
    p("External evidence references", { bold: true, size: 22 }),
    ...(d.evidence.externalReferences.length === 0
      ? [p("None.", { color: "808080" })]
      : d.evidence.externalReferences.map((e) =>
          linkParagraph(e.title || "Reference", e.url),
        )),
    p("Same-project BTPM context links", { bold: true, size: 22 }),
    ...(d.evidence.btpmContextLinks.length === 0
      ? [p("None.", { color: "808080" })]
      : bulletList(
          d.evidence.btpmContextLinks.map(
            (l) => `${l.linked_object_type} · ${l.linked_object_id}`,
          ),
        )),
    p("Cross-project context links", { bold: true, size: 22 }),
    ...(d.evidence.crossProjectLinks.length === 0
      ? [p("None.", { color: "808080" })]
      : bulletList(
          d.evidence.crossProjectLinks.map(
            (l) => `${l.label || "Linked project"}${l.reason ? ` — ${l.reason}` : ""}`,
          ),
        )),

    // Conditions / Guardrails
    heading("Conditions / Guardrails"),
    ...bodyOrPlaceholder(d.package.guardrails),

    // Residual Risks
    heading("Residual Risks"),
    ...bodyOrPlaceholder(d.package.residualRisks),

    // Decision Outcome
    heading("Decision Outcome"),
    ...(d.outcome
      ? [
          p(`Result: ${statusLabel(d.outcome.decisionResult)}`),
          p(`Decision date: ${fmtDate(d.outcome.decisionDate)}`),
          p(`Decided by: ${d.outcome.decidedBy || "—"}`),
          p(`Approval forum: ${d.outcome.approvalForum || "—"}`),
          p(`Sign-off status: ${statusLabel(d.outcome.signoffStatus)}`),
          ...(d.outcome.signoffEvidenceUrl
            ? [linkParagraph("Sign-off evidence", d.outcome.signoffEvidenceUrl)]
            : []),
          p(
            `Implementation target date: ${fmtDate(d.outcome.implementationTargetDate)}`,
          ),
          p("Final decision", { bold: true }),
          ...bodyOrPlaceholder(d.outcome.finalDecisionText),
          p("Rationale", { bold: true }),
          ...bodyOrPlaceholder(d.outcome.rationale),
          p("Conditions / Guardrails", { bold: true }),
          ...bodyOrPlaceholder(d.outcome.conditionsGuardrails),
          p("Residual risks", { bold: true }),
          ...bodyOrPlaceholder(d.outcome.residualRisks),
          p("Follow-up actions", { bold: true }),
          ...bodyOrPlaceholder(d.outcome.followUpActions),
          ...(d.outcome.closureNote
            ? [p("Closure note", { bold: true }), ...bodyOrPlaceholder(d.outcome.closureNote)]
            : []),
        ]
      : [p("Decision outcome not recorded yet.", { color: "808080" })]),

    // Next Steps
    heading("Next Steps / Follow-up Actions"),
    ...bodyOrPlaceholder(d.package.nextSteps),

    // Source and Governance Note
    new Paragraph({ children: [new PageBreak()] }),
    heading("Source and Governance Note"),
    p(
      "This document is a generated snapshot from BTPM. The source of truth remains the Decision Case in BTPM.",
    ),
    p(
      `Snapshot taken: ${fmtDate(d.generatedAt)} · Stakeholder package version: v${d.package.versionNumber} · Package status: ${statusLabel(d.package.status)}.`,
      { color: "808080" },
    ),
  ];

  const doc = new Document({
    creator: "BTPM",
    title: titleLine,
    description: "BTPM generated Decision Brief",
    styles: {
      default: { document: { run: { font: FONT, size: 22 } } },
      paragraphStyles: [
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 30, bold: true, color: "1F3A5F", font: FONT },
          paragraph: { spacing: { before: 320, after: 160 }, outlineLevel: 0 },
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 26, bold: true, color: "2E5984", font: FONT },
          paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 1 },
        },
      ],
    },
    numbering: {
      config: [
        {
          reference: "bullets",
          levels: [
            {
              level: 0,
              format: LevelFormat.BULLET,
              text: "\u2022",
              alignment: AlignmentType.LEFT,
              style: { paragraph: { indent: { left: 720, hanging: 360 } } },
            },
          ],
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            size: { width: 12240, height: 15840 },
            margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: `BTPM · Decision Brief · ${d.decisionCase.title}`,
                    size: 18,
                    color: "808080",
                    font: FONT,
                  }),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: "BTPM · Generated ", size: 18, color: "808080", font: FONT }),
                  new TextRun({ text: fmtDate(d.generatedAt), size: 18, color: "808080", font: FONT }),
                  new TextRun({ text: ` · v${d.package.versionNumber} · Page `, size: 18, color: "808080", font: FONT }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 18, color: "808080", font: FONT }),
                  new TextRun({ text: " of ", size: 18, color: "808080", font: FONT }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 18, color: "808080", font: FONT }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return new Uint8Array(buffer);
}
