-- BTPM OSS baseline: current Project-to-Portfolio assignment private bridge.
CREATE OR REPLACE FUNCTION api_e_private.execute_v1_assign_project_portfolio(
  _execution_source text,_expected_oauth_client_id text,_project_id uuid,_portfolio_item_id uuid,
  _request_id text,_correlation_id text,_idempotency_key text,_payload_hash text
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog','public' AS $function$
DECLARE
  c_api_version constant text:='v1';c_capability_kind constant text:='command';c_capability_key constant text:='portfolios:assign_project';
  v_source text:=_execution_source;v_source_channel public.pmg_source_channel;v_project_id uuid;v_organization_id uuid;v_workspace_id uuid;v_current_portfolio_id uuid;
  v_trusted boolean:=false;v_ctx_user_id uuid;v_ctx_client_id uuid;v_ctx_tenant_id uuid;v_ctx_org_id uuid;v_ctx_workspace_id uuid;v_ctx_api_version text;v_ctx_capability_kind text;v_ctx_capability_key text;v_ctx_source_channel text;v_enabled boolean:=false;
  v_claim record;v_locked_project_id uuid;v_locked_org_id uuid;v_locked_workspace_id uuid;v_locked_old_portfolio_id uuid;v_target_org_id uuid;v_target_archived boolean;v_final_portfolio_id uuid;v_outcome text;v_result jsonb;
BEGIN
  IF v_source IS NULL OR v_source NOT IN ('external_api','mcp') THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
  v_source_channel:=CASE WHEN v_source='external_api' THEN 'external_api'::public.pmg_source_channel ELSE 'mcp'::public.pmg_source_channel END;
  IF nullif(btrim(coalesce(_expected_oauth_client_id,'')),'') IS NULL OR length(_expected_oauth_client_id)>255 OR _project_id IS NULL
     OR coalesce(nullif(btrim(coalesce(_request_id,'')),''),'') !~ '^[A-Za-z0-9._~:@/-]{1,128}$'
     OR coalesce(nullif(btrim(coalesce(_correlation_id,'')),''),'') !~ '^[A-Za-z0-9._~:@/-]{1,128}$'
     OR coalesce(nullif(btrim(coalesce(_idempotency_key,'')),''),'') !~ '^[A-Za-z0-9._~:@/+!=-]{1,255}$'
     OR coalesce(_payload_hash,'') !~ '^[0-9a-f]{64}$' THEN RETURN jsonb_build_object('ok',false,'outcome','invalid');END IF;
  SELECT p.id,p.organization_id,p.workspace_id,p.portfolio_item_id INTO v_project_id,v_organization_id,v_workspace_id,v_current_portfolio_id FROM public.projects p WHERE p.id=_project_id;
  IF v_project_id IS NULL OR v_organization_id IS NULL OR v_workspace_id IS NULL THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
  IF v_source='external_api' THEN BEGIN v_trusted:=api_e_private.authorize_and_establish(_expected_oauth_client_id,v_organization_id,v_workspace_id,c_api_version,c_capability_kind,c_capability_key,_request_id);EXCEPTION WHEN OTHERS THEN v_trusted:=false;END;
  ELSE BEGIN v_trusted:=api_e_private.authorize_and_establish_mcp(_expected_oauth_client_id,v_organization_id,v_workspace_id,c_api_version,c_capability_kind,c_capability_key,_request_id);EXCEPTION WHEN OTHERS THEN v_trusted:=false;END;END IF;
  IF v_trusted IS NOT TRUE THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
  BEGIN v_ctx_user_id:=nullif(btrim(coalesce(current_setting('api_e.executing_user_id',true),'')),'')::uuid;v_ctx_client_id:=nullif(btrim(coalesce(current_setting('api_e.api_client_id',true),'')),'')::uuid;v_ctx_tenant_id:=nullif(btrim(coalesce(current_setting('api_e.tenant_id',true),'')),'')::uuid;v_ctx_org_id:=nullif(btrim(coalesce(current_setting('api_e.organization_id',true),'')),'')::uuid;v_ctx_workspace_id:=nullif(btrim(coalesce(current_setting('api_e.workspace_id',true),'')),'')::uuid;EXCEPTION WHEN OTHERS THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END;
  v_ctx_api_version:=nullif(btrim(coalesce(current_setting('api_e.api_version',true),'')),'');v_ctx_capability_kind:=nullif(btrim(coalesce(current_setting('api_e.capability_kind',true),'')),'');v_ctx_capability_key:=nullif(btrim(coalesce(current_setting('api_e.capability_key',true),'')),'');v_ctx_source_channel:=nullif(btrim(coalesce(current_setting('api_e.source_channel',true),'')),'');
  IF nullif(btrim(coalesce(current_setting('api_e.trusted',true),'')),'') IS DISTINCT FROM 'true' OR v_ctx_user_id IS NULL OR v_ctx_client_id IS NULL OR v_ctx_tenant_id IS NULL OR v_ctx_org_id IS DISTINCT FROM v_organization_id OR v_ctx_workspace_id IS DISTINCT FROM v_workspace_id OR v_ctx_api_version IS DISTINCT FROM c_api_version OR v_ctx_capability_kind IS DISTINCT FROM c_capability_kind OR v_ctx_capability_key IS DISTINCT FROM c_capability_key OR v_ctx_source_channel IS DISTINCT FROM v_source THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
  SELECT true INTO v_enabled FROM public.api_project_client_enablements e WHERE e.project_id=v_project_id AND e.api_client_id=v_ctx_client_id AND e.tenant_id=v_ctx_tenant_id AND e.organization_id=v_organization_id AND e.workspace_id=v_workspace_id AND e.lifecycle_status='enabled' AND e.enabled_at IS NOT NULL AND e.disabled_at IS NULL LIMIT 1;
  IF v_enabled IS NOT TRUE OR NOT public.has_project_pm_authority(v_ctx_user_id,_project_id) OR NOT public.can_write_demo(v_ctx_user_id,v_workspace_id) THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
  SELECT c.decision,c.registry_id,c.registry_state,c.canonical_result,c.failure_code INTO v_claim FROM api_e_private.claim_idempotency(c_capability_key,_idempotency_key,_payload_hash)c;
  IF v_claim.decision IS NULL THEN RAISE EXCEPTION 'execute_v1_assign_project_portfolio: no idempotency claim decision' USING ERRCODE='XX000';END IF;
  IF v_claim.decision='conflict' THEN RETURN jsonb_build_object('ok',false,'outcome','idempotency_conflict');ELSIF v_claim.decision='pending' THEN RETURN jsonb_build_object('ok',false,'outcome','idempotency_pending');ELSIF v_claim.decision='replay' THEN IF v_claim.registry_state='completed' THEN IF v_claim.canonical_result IS NULL OR jsonb_typeof(v_claim.canonical_result)<>'object' THEN RAISE EXCEPTION 'execute_v1_assign_project_portfolio: invalid stored canonical result' USING ERRCODE='XX000';END IF;RETURN v_claim.canonical_result||jsonb_build_object('outcome','replayed');ELSIF v_claim.registry_state='failed' THEN IF v_claim.failure_code='not_authorized' THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');ELSIF v_claim.failure_code='invalid' THEN RETURN jsonb_build_object('ok',false,'outcome','invalid');END IF;RAISE EXCEPTION 'execute_v1_assign_project_portfolio: unknown persisted failure code' USING ERRCODE='XX000';END IF;RAISE EXCEPTION 'execute_v1_assign_project_portfolio: unexpected replay state' USING ERRCODE='XX000';ELSIF v_claim.decision<>'execute' THEN RAISE EXCEPTION 'execute_v1_assign_project_portfolio: unexpected idempotency decision' USING ERRCODE='XX000';END IF;
  SELECT p.id,p.organization_id,p.workspace_id,p.portfolio_item_id INTO v_locked_project_id,v_locked_org_id,v_locked_workspace_id,v_locked_old_portfolio_id FROM public.projects p WHERE p.id=_project_id FOR UPDATE;
  IF v_locked_project_id IS NULL OR v_locked_org_id IS DISTINCT FROM v_organization_id OR v_locked_workspace_id IS DISTINCT FROM v_workspace_id THEN PERFORM api_e_private.fail_idempotency(v_claim.registry_id,'not_authorized');RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
  IF _portfolio_item_id IS NOT NULL THEN SELECT pi.organization_id,pi.is_archived INTO v_target_org_id,v_target_archived FROM public.portfolio_items pi WHERE pi.id=_portfolio_item_id FOR UPDATE; IF v_target_org_id IS NULL OR v_target_org_id IS DISTINCT FROM v_organization_id OR v_target_archived IS NOT FALSE THEN PERFORM api_e_private.fail_idempotency(v_claim.registry_id,'invalid');RETURN jsonb_build_object('ok',false,'outcome','invalid');END IF;END IF;
  PERFORM public.assign_project_portfolio(_project_id,_portfolio_item_id);SELECT p.portfolio_item_id INTO v_final_portfolio_id FROM public.projects p WHERE p.id=_project_id;IF v_final_portfolio_id IS DISTINCT FROM _portfolio_item_id THEN RAISE EXCEPTION 'execute_v1_assign_project_portfolio: canonical assignment verification failed' USING ERRCODE='XX000';END IF;
  v_outcome:=CASE WHEN v_locked_old_portfolio_id IS NOT DISTINCT FROM _portfolio_item_id THEN 'no_change' ELSE 'applied' END;
  PERFORM public.pmg_record_command_audit(v_outcome::public.pmg_command_status,'assign_project_portfolio',v_source_channel,_project_id,'project',_project_id,NULL,_correlation_id,_idempotency_key,jsonb_build_object('old_portfolio_id',v_locked_old_portfolio_id,'new_portfolio_id',_portfolio_item_id,'assignment_cleared',(_portfolio_item_id IS NULL)));
  v_result:=jsonb_build_object('ok',true,'outcome',v_outcome,'projectId',_project_id,'oldPortfolioId',v_locked_old_portfolio_id,'newPortfolioId',_portfolio_item_id);PERFORM api_e_private.complete_idempotency(v_claim.registry_id,v_result);RETURN v_result;
END;$function$;
REVOKE ALL ON FUNCTION api_e_private.execute_v1_assign_project_portfolio(text,text,uuid,uuid,text,text,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION api_e_private.execute_v1_assign_project_portfolio(text,text,uuid,uuid,text,text,text,text) FROM anon;
REVOKE ALL ON FUNCTION api_e_private.execute_v1_assign_project_portfolio(text,text,uuid,uuid,text,text,text,text) FROM authenticated;
REVOKE ALL ON FUNCTION api_e_private.execute_v1_assign_project_portfolio(text,text,uuid,uuid,text,text,text,text) FROM service_role;
