-- BTPM OSS baseline: current Risk Create and Update private execution bridges.
CREATE OR REPLACE FUNCTION api_e_private.execute_v1_create_risk(
 _execution_source text,_expected_oauth_client_id text,_target_type text,_target_id uuid,_title text,_description text,_mitigation_plan text,_likelihood text,_impact text,_status text,_request_id text,_correlation_id text,_idempotency_key text,_payload_hash text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog','public' AS $function$
DECLARE c_api_version constant text:='v1';c_capability_kind constant text:='command';c_capability_key constant text:='risks:create';v_source text:=_execution_source;v_target_type text:=lower(nullif(btrim(coalesce(_target_type,'')),''));v_project_id uuid;v_workspace_id uuid;v_organization_id uuid;v_trusted boolean:=false;v_ctx_client_id uuid;v_ctx_tenant_id uuid;v_ctx_org_id uuid;v_ctx_workspace_id uuid;v_enabled boolean:=false;v_claim record;v_pmg jsonb;v_status text;v_data jsonb;v_risk_id uuid;v_result jsonb;
BEGIN
 IF v_source IS NULL OR v_source NOT IN ('external_api','mcp') THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
 IF nullif(btrim(coalesce(_expected_oauth_client_id,'')),'') IS NULL OR v_target_type IS NULL OR v_target_type NOT IN ('project','phase','task') OR _target_id IS NULL OR coalesce(nullif(btrim(coalesce(_request_id,'')),''),'') !~ '^[A-Za-z0-9._~:@/-]{1,128}$' OR coalesce(nullif(btrim(coalesce(_correlation_id,'')),''),'') !~ '^[A-Za-z0-9._~:@/-]{1,128}$' OR coalesce(nullif(btrim(coalesce(_idempotency_key,'')),''),'') !~ '^[A-Za-z0-9._~:@/+!=-]{1,255}$' OR coalesce(_payload_hash,'') !~ '^[0-9a-f]{64}$' THEN RETURN jsonb_build_object('ok',false,'outcome','invalid');END IF;
 IF v_target_type='project' THEN SELECT p.id,p.workspace_id,p.organization_id INTO v_project_id,v_workspace_id,v_organization_id FROM public.projects p WHERE p.id=_target_id;ELSIF v_target_type='phase' THEN SELECT p.id,p.workspace_id,p.organization_id INTO v_project_id,v_workspace_id,v_organization_id FROM public.phases ph JOIN public.projects p ON p.id=ph.project_id WHERE ph.id=_target_id;ELSE SELECT p.id,p.workspace_id,p.organization_id INTO v_project_id,v_workspace_id,v_organization_id FROM public.tasks t JOIN public.projects p ON p.id=t.project_id LEFT JOIN public.phases ph ON ph.id=t.phase_id WHERE t.id=_target_id AND (t.phase_id IS NULL OR ph.project_id=t.project_id);END IF;
 IF v_project_id IS NULL OR v_workspace_id IS NULL OR v_organization_id IS NULL THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
 IF v_source='external_api' THEN BEGIN v_trusted:=api_e_private.authorize_and_establish(_expected_oauth_client_id,v_organization_id,v_workspace_id,c_api_version,c_capability_kind,c_capability_key,_request_id);EXCEPTION WHEN OTHERS THEN v_trusted:=false;END;ELSE BEGIN v_trusted:=api_e_private.authorize_and_establish_mcp(_expected_oauth_client_id,v_organization_id,v_workspace_id,c_api_version,c_capability_kind,c_capability_key,_request_id);EXCEPTION WHEN OTHERS THEN v_trusted:=false;END;END IF;IF v_trusted IS NOT TRUE THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
 BEGIN v_ctx_client_id:=nullif(btrim(coalesce(current_setting('api_e.api_client_id',true),'')),'')::uuid;v_ctx_tenant_id:=nullif(btrim(coalesce(current_setting('api_e.tenant_id',true),'')),'')::uuid;v_ctx_org_id:=nullif(btrim(coalesce(current_setting('api_e.organization_id',true),'')),'')::uuid;v_ctx_workspace_id:=nullif(btrim(coalesce(current_setting('api_e.workspace_id',true),'')),'')::uuid;EXCEPTION WHEN OTHERS THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END;
 IF v_ctx_client_id IS NULL OR v_ctx_tenant_id IS NULL OR v_ctx_org_id IS DISTINCT FROM v_organization_id OR v_ctx_workspace_id IS DISTINCT FROM v_workspace_id THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
 SELECT true INTO v_enabled FROM public.api_project_client_enablements e WHERE e.project_id=v_project_id AND e.api_client_id=v_ctx_client_id AND e.tenant_id=v_ctx_tenant_id AND e.organization_id=v_organization_id AND e.workspace_id=v_workspace_id AND e.lifecycle_status='enabled' AND e.enabled_at IS NOT NULL AND e.disabled_at IS NULL LIMIT 1;IF v_enabled IS NOT TRUE THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
 SELECT c.decision,c.registry_id,c.registry_state,c.canonical_result,c.failure_code INTO v_claim FROM api_e_private.claim_idempotency(c_capability_key,_idempotency_key,_payload_hash)c;IF v_claim.decision IS NULL THEN RAISE EXCEPTION 'api_v1_create_risk: no idempotency claim decision' USING ERRCODE='XX000';END IF;
 IF v_claim.decision='conflict' THEN RETURN jsonb_build_object('ok',false,'outcome','idempotency_conflict');ELSIF v_claim.decision='pending' THEN RETURN jsonb_build_object('ok',false,'outcome','idempotency_pending');ELSIF v_claim.decision='replay' THEN IF v_claim.registry_state='completed' THEN IF v_claim.canonical_result IS NULL OR jsonb_typeof(v_claim.canonical_result)<>'object' THEN RAISE EXCEPTION 'api_v1_create_risk: invalid stored canonical result' USING ERRCODE='XX000';END IF;RETURN v_claim.canonical_result||jsonb_build_object('outcome','replayed');ELSIF v_claim.registry_state='failed' THEN IF v_claim.failure_code='not_authorized' THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');ELSIF v_claim.failure_code='invalid' THEN RETURN jsonb_build_object('ok',false,'outcome','invalid');END IF;RAISE EXCEPTION 'api_v1_create_risk: unknown persisted failure code' USING ERRCODE='XX000';END IF;RAISE EXCEPTION 'api_v1_create_risk: unexpected replay state' USING ERRCODE='XX000';ELSIF v_claim.decision<>'execute' THEN RAISE EXCEPTION 'api_v1_create_risk: unexpected idempotency decision' USING ERRCODE='XX000';END IF;
 v_pmg:=public.apply_risk_create(v_target_type,_target_id,_title,_description,_mitigation_plan,_likelihood,_impact,_status,'[]'::jsonb,'[]'::jsonb,_correlation_id,_idempotency_key);v_status:=v_pmg->>'status';v_data:=coalesce(v_pmg->'data','{}'::jsonb);
 IF v_status='applied' THEN BEGIN v_risk_id:=nullif(btrim(coalesce(v_data->>'id','')),'')::uuid;EXCEPTION WHEN OTHERS THEN RAISE EXCEPTION 'api_v1_create_risk: malformed applied result' USING ERRCODE='XX000';END;IF v_risk_id IS NULL OR (v_data->>'target_type') IS DISTINCT FROM v_target_type OR (v_data->>'target_id') IS DISTINCT FROM _target_id::text OR nullif(btrim(coalesce(v_data->>'likelihood','')),'') IS NULL OR nullif(btrim(coalesce(v_data->>'impact','')),'') IS NULL OR nullif(btrim(coalesce(v_data->>'status','')),'') IS NULL OR nullif(btrim(coalesce(v_data->>'created_at','')),'') IS NULL OR nullif(btrim(coalesce(v_data->>'updated_at','')),'') IS NULL THEN RAISE EXCEPTION 'api_v1_create_risk: inconsistent applied result' USING ERRCODE='XX000';END IF;v_result:=jsonb_build_object('ok',true,'outcome','applied','riskId',v_risk_id,'targetType',v_target_type,'targetId',_target_id,'likelihood',v_data->>'likelihood','impact',v_data->>'impact','status',v_data->>'status','createdAt',v_data->>'created_at','updatedAt',v_data->>'updated_at');PERFORM api_e_private.complete_idempotency(v_claim.registry_id,v_result);RETURN v_result;ELSIF v_status='not_authorized' THEN PERFORM api_e_private.fail_idempotency(v_claim.registry_id,'not_authorized');RETURN jsonb_build_object('ok',false,'outcome','not_authorized');ELSIF v_status='invalid' THEN PERFORM api_e_private.fail_idempotency(v_claim.registry_id,'invalid');RETURN jsonb_build_object('ok',false,'outcome','invalid');END IF;RAISE EXCEPTION 'api_v1_create_risk: unexpected canonical command status' USING ERRCODE='XX000';
END;$function$;
REVOKE ALL ON FUNCTION api_e_private.execute_v1_create_risk(text,text,text,uuid,text,text,text,text,text,text,text,text,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION api_e_private.execute_v1_create_risk(text,text,text,uuid,text,text,text,text,text,text,text,text,text,text) FROM anon;
REVOKE ALL ON FUNCTION api_e_private.execute_v1_create_risk(text,text,text,uuid,text,text,text,text,text,text,text,text,text,text) FROM authenticated;
REVOKE ALL ON FUNCTION api_e_private.execute_v1_create_risk(text,text,text,uuid,text,text,text,text,text,text,text,text,text,text) FROM service_role;

CREATE OR REPLACE FUNCTION api_e_private.execute_v1_update_risk(
 _execution_source text,_expected_oauth_client_id text,_risk_id uuid,_expected_updated_at timestamptz,_title text,_description text,_mitigation_plan text,_likelihood text,_impact text,_status text,_request_id text,_correlation_id text,_idempotency_key text,_payload_hash text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog','public' AS $function$
DECLARE c_api_version constant text:='v1';c_capability_kind constant text:='command';c_capability_key constant text:='risks:update';v_source text:=_execution_source;v_row_target_type text;v_row_target_id uuid;v_row_workspace_id uuid;v_row_organization_id uuid;v_project_id uuid;v_workspace_id uuid;v_organization_id uuid;v_trusted boolean:=false;v_ctx_client_id uuid;v_ctx_tenant_id uuid;v_ctx_org_id uuid;v_ctx_workspace_id uuid;v_enabled boolean:=false;v_claim record;v_locked_target_type text;v_locked_target_id uuid;v_locked_workspace_id uuid;v_locked_organization_id uuid;v_user_links jsonb;v_object_links jsonb;v_pmg jsonb;v_status text;v_data jsonb;v_result jsonb;
BEGIN
 IF v_source IS NULL OR v_source NOT IN ('external_api','mcp') THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
 IF nullif(btrim(coalesce(_expected_oauth_client_id,'')),'') IS NULL OR _risk_id IS NULL OR _expected_updated_at IS NULL OR coalesce(nullif(btrim(coalesce(_request_id,'')),''),'') !~ '^[A-Za-z0-9._~:@/-]{1,128}$' OR coalesce(nullif(btrim(coalesce(_correlation_id,'')),''),'') !~ '^[A-Za-z0-9._~:@/-]{1,128}$' OR coalesce(nullif(btrim(coalesce(_idempotency_key,'')),''),'') !~ '^[A-Za-z0-9._~:@/+!=-]{1,255}$' OR coalesce(_payload_hash,'') !~ '^[0-9a-f]{64}$' THEN RETURN jsonb_build_object('ok',false,'outcome','invalid');END IF;
 SELECT r.target_type,r.target_id,r.workspace_id,r.organization_id INTO v_row_target_type,v_row_target_id,v_row_workspace_id,v_row_organization_id FROM public.risks r WHERE r.id=_risk_id;IF v_row_target_type IS NULL OR v_row_target_id IS NULL THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
 IF v_row_target_type='project' THEN SELECT p.id,p.workspace_id,p.organization_id INTO v_project_id,v_workspace_id,v_organization_id FROM public.projects p WHERE p.id=v_row_target_id;ELSIF v_row_target_type='phase' THEN SELECT p.id,p.workspace_id,p.organization_id INTO v_project_id,v_workspace_id,v_organization_id FROM public.phases ph JOIN public.projects p ON p.id=ph.project_id WHERE ph.id=v_row_target_id;ELSIF v_row_target_type='task' THEN SELECT p.id,p.workspace_id,p.organization_id INTO v_project_id,v_workspace_id,v_organization_id FROM public.tasks t JOIN public.projects p ON p.id=t.project_id LEFT JOIN public.phases ph ON ph.id=t.phase_id WHERE t.id=v_row_target_id AND (t.phase_id IS NULL OR ph.project_id=t.project_id);END IF;
 IF v_project_id IS NULL OR v_workspace_id IS NULL OR v_organization_id IS NULL OR v_workspace_id IS DISTINCT FROM v_row_workspace_id OR v_organization_id IS DISTINCT FROM v_row_organization_id THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
 IF v_source='external_api' THEN BEGIN v_trusted:=api_e_private.authorize_and_establish(_expected_oauth_client_id,v_organization_id,v_workspace_id,c_api_version,c_capability_kind,c_capability_key,_request_id);EXCEPTION WHEN OTHERS THEN v_trusted:=false;END;ELSE BEGIN v_trusted:=api_e_private.authorize_and_establish_mcp(_expected_oauth_client_id,v_organization_id,v_workspace_id,c_api_version,c_capability_kind,c_capability_key,_request_id);EXCEPTION WHEN OTHERS THEN v_trusted:=false;END;END IF;IF v_trusted IS NOT TRUE THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
 BEGIN v_ctx_client_id:=nullif(btrim(coalesce(current_setting('api_e.api_client_id',true),'')),'')::uuid;v_ctx_tenant_id:=nullif(btrim(coalesce(current_setting('api_e.tenant_id',true),'')),'')::uuid;v_ctx_org_id:=nullif(btrim(coalesce(current_setting('api_e.organization_id',true),'')),'')::uuid;v_ctx_workspace_id:=nullif(btrim(coalesce(current_setting('api_e.workspace_id',true),'')),'')::uuid;EXCEPTION WHEN OTHERS THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END;IF v_ctx_client_id IS NULL OR v_ctx_tenant_id IS NULL OR v_ctx_org_id IS DISTINCT FROM v_organization_id OR v_ctx_workspace_id IS DISTINCT FROM v_workspace_id THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
 SELECT true INTO v_enabled FROM public.api_project_client_enablements e WHERE e.project_id=v_project_id AND e.api_client_id=v_ctx_client_id AND e.tenant_id=v_ctx_tenant_id AND e.organization_id=v_organization_id AND e.workspace_id=v_workspace_id AND e.lifecycle_status='enabled' AND e.enabled_at IS NOT NULL AND e.disabled_at IS NULL LIMIT 1;IF v_enabled IS NOT TRUE THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
 SELECT c.decision,c.registry_id,c.registry_state,c.canonical_result,c.failure_code INTO v_claim FROM api_e_private.claim_idempotency(c_capability_key,_idempotency_key,_payload_hash)c;IF v_claim.decision IS NULL THEN RAISE EXCEPTION 'api_v1_update_risk: no idempotency claim decision' USING ERRCODE='XX000';END IF;
 IF v_claim.decision='conflict' THEN RETURN jsonb_build_object('ok',false,'outcome','idempotency_conflict');ELSIF v_claim.decision='pending' THEN RETURN jsonb_build_object('ok',false,'outcome','idempotency_pending');ELSIF v_claim.decision='replay' THEN IF v_claim.registry_state='completed' THEN IF v_claim.canonical_result IS NULL OR jsonb_typeof(v_claim.canonical_result)<>'object' THEN RAISE EXCEPTION 'api_v1_update_risk: invalid stored canonical result' USING ERRCODE='XX000';END IF;RETURN v_claim.canonical_result||jsonb_build_object('outcome','replayed');ELSIF v_claim.registry_state='failed' THEN IF v_claim.failure_code='stale_risk' THEN RETURN jsonb_build_object('ok',false,'outcome','conflict','code','stale_risk');ELSIF v_claim.failure_code='not_authorized' THEN RETURN jsonb_build_object('ok',false,'outcome','not_authorized');ELSIF v_claim.failure_code='invalid' THEN RETURN jsonb_build_object('ok',false,'outcome','invalid');END IF;RAISE EXCEPTION 'api_v1_update_risk: unknown persisted failure code' USING ERRCODE='XX000';END IF;RAISE EXCEPTION 'api_v1_update_risk: unexpected replay state' USING ERRCODE='XX000';ELSIF v_claim.decision<>'execute' THEN RAISE EXCEPTION 'api_v1_update_risk: unexpected idempotency decision' USING ERRCODE='XX000';END IF;
 SELECT r.target_type,r.target_id,r.workspace_id,r.organization_id INTO v_locked_target_type,v_locked_target_id,v_locked_workspace_id,v_locked_organization_id FROM public.risks r WHERE r.id=_risk_id FOR UPDATE;IF v_locked_target_type IS DISTINCT FROM v_row_target_type OR v_locked_target_id IS DISTINCT FROM v_row_target_id OR v_locked_workspace_id IS DISTINCT FROM v_workspace_id OR v_locked_organization_id IS DISTINCT FROM v_organization_id THEN PERFORM api_e_private.fail_idempotency(v_claim.registry_id,'not_authorized');RETURN jsonb_build_object('ok',false,'outcome','not_authorized');END IF;
 SELECT coalesce(jsonb_agg(jsonb_build_object('user_id',eul.user_id,'stakeholder_id',eul.stakeholder_id) ORDER BY eul.sort_order,eul.id),'[]'::jsonb) INTO v_user_links FROM public.entity_user_links eul WHERE eul.owner_type='risk' AND eul.owner_id=_risk_id AND eul.link_role='related_person';SELECT coalesce(jsonb_agg(jsonb_build_object('referenced_type',eol.referenced_type,'referenced_id',eol.referenced_id) ORDER BY eol.sort_order,eol.id),'[]'::jsonb) INTO v_object_links FROM public.entity_object_links eol WHERE eol.owner_type='risk' AND eol.owner_id=_risk_id AND eol.link_role='related_object';
 v_pmg:=public.apply_risk_update(_risk_id,_expected_updated_at,_title,_description,_mitigation_plan,_likelihood,_impact,_status,v_user_links,v_object_links,_correlation_id,_idempotency_key);v_status:=v_pmg->>'status';v_data:=coalesce(v_pmg->'data','{}'::jsonb);
 IF v_status IN ('applied','no_change') THEN IF (v_data->>'id') IS DISTINCT FROM _risk_id::text OR (v_data->>'target_type') IS DISTINCT FROM v_row_target_type OR (v_data->>'target_id') IS DISTINCT FROM v_row_target_id::text OR nullif(btrim(coalesce(v_data->>'likelihood','')),'') IS NULL OR nullif(btrim(coalesce(v_data->>'impact','')),'') IS NULL OR nullif(btrim(coalesce(v_data->>'status','')),'') IS NULL OR nullif(btrim(coalesce(v_data->>'updated_at','')),'') IS NULL THEN RAISE EXCEPTION 'api_v1_update_risk: inconsistent canonical result' USING ERRCODE='XX000';END IF;v_result:=jsonb_build_object('ok',true,'outcome',v_status,'riskId',_risk_id,'targetType',v_row_target_type,'targetId',v_row_target_id,'likelihood',v_data->>'likelihood','impact',v_data->>'impact','status',v_data->>'status','updatedAt',v_data->>'updated_at');PERFORM api_e_private.complete_idempotency(v_claim.registry_id,v_result);RETURN v_result;ELSIF v_status='conflict' THEN PERFORM api_e_private.fail_idempotency(v_claim.registry_id,'stale_risk');RETURN jsonb_build_object('ok',false,'outcome','conflict','code','stale_risk');ELSIF v_status='not_authorized' THEN PERFORM api_e_private.fail_idempotency(v_claim.registry_id,'not_authorized');RETURN jsonb_build_object('ok',false,'outcome','not_authorized');ELSIF v_status='invalid' THEN PERFORM api_e_private.fail_idempotency(v_claim.registry_id,'invalid');RETURN jsonb_build_object('ok',false,'outcome','invalid');END IF;RAISE EXCEPTION 'api_v1_update_risk: unexpected canonical command status' USING ERRCODE='XX000';
END;$function$;
REVOKE ALL ON FUNCTION api_e_private.execute_v1_update_risk(text,text,uuid,timestamptz,text,text,text,text,text,text,text,text,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION api_e_private.execute_v1_update_risk(text,text,uuid,timestamptz,text,text,text,text,text,text,text,text,text,text) FROM anon;
REVOKE ALL ON FUNCTION api_e_private.execute_v1_update_risk(text,text,uuid,timestamptz,text,text,text,text,text,text,text,text,text,text) FROM authenticated;
REVOKE ALL ON FUNCTION api_e_private.execute_v1_update_risk(text,text,uuid,timestamptz,text,text,text,text,text,text,text,text,text,text) FROM service_role;
