// AUTO-GENERATED by scripts/generate-release-metadata.mjs — do not edit by hand.
export const APP_VERSION = "1.5.70";
export const BUILD_VERSION = "1.5.70+20260823T133230Z";
export const RELEASED_AT_UTC = "2026-08-23T13:32:30.535Z";
